### ISSUE TITLE
Question regarding your ci release

### ISSUE THREAD

**Issue by The-Code-Monkey** [FRSOURCE/tiny-carousel#286]
Your repo has been super helpful to me for helping me setup lerna on mine. In regards to dependabot updating packages does lerna release a new version each time one of those updates as current my repo doesn't, sorry for using this to get into contact for help

**Comment by FRSgit** [comment]
Nope, as you can see - it doesn't. It seems that lerna has problems (or doesn't check at all) the `yarn.lock` in workspace root for potential file changes (you can see [this example action run from main branch to see that lerna says no file has been changed](https://github.com/FRSOURCE/tiny-carousel/runs/5680141658?check_suite_focus=true#step:12:35)).

**Comment by The-Code-Monkey** [comment]
Ok thank you for your reply. Sorry to bother you.
